theme: jekyll-theme-cayman
title: "Introduction to Proxy System Models"
colors:
    gradient_left: "#020344"
    gradient_right: "#28B8D5"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#020344" # this default to gradient_color
